# Generated by Django 3.2.7 on 2022-02-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('position', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=10)),
                ('last_payment', models.DateTimeField()),
                ('bank_account', models.CharField(max_length=26, unique=True)),
            ],
        ),
    ]
